/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface BatchResponse {
  keys: Array<string>
  values?: Array<any>
}
export declare function startLogger(): void
export declare function initCouchbase(): void
export declare function getDocuments(key: string, withCas: boolean, bucketName: string): Promise<any>
export declare function addDocument(key: string, value: any, bucketName: string): Promise<boolean>
export declare function replaceDocument(key: string, value: any, withCas: bigint | null | undefined, bucketName: string): Promise<boolean>
export declare function removeDocument(key: string, bucketName: string): Promise<string>
export declare function getBatchDocuments(keys: Array<string>, withCas: boolean, bucketName: string): Promise<any>
export declare function getBatchDocumentsV2(keys: Array<string>, withCas: boolean, bucketName: string): Promise<any>
